import * as React from 'react'
import { Loader2, History } from 'lucide-react'
import { ActionBadge } from '@/components/shared/UICommons'
import type { ActivityLog } from '@/hooks/useAudit'
import { actionVerbFor, formatChangeEntries } from '@/lib/activityFormat'
import { formatDateTime } from '@/lib/utils'

/**
 * Shared employee-activity feed used by:
 *   - HR view: Employee detail page → "Updates" tab
 *   - Employee view: /my/activity page
 *
 * Reads metadata.kind / metadata.subKind set by backend modules (documents,
 * attendance, payroll, leave, loans, visa, transfers, exit, assets,
 * performance, profile, security) and renders a human-readable headline +
 * context pills + a from/to change list when applicable.
 */

function formatPunchTime(iso?: string | null): string {
    if (!iso) return ''
    const d = new Date(iso)
    if (Number.isNaN(d.getTime())) return ''
    return d.toLocaleString('en-AE', { hour: '2-digit', minute: '2-digit', day: 'numeric', month: 'short' })
}

function buildActivityHeadline(log: ActivityLog, changeCount: number, viewer: 'hr' | 'self'): React.ReactNode {
    const meta = (log.metadata ?? {}) as Record<string, unknown>
    const kind = typeof meta.kind === 'string' ? meta.kind : null
    const subKind = typeof meta.subKind === 'string' ? meta.subKind : null
    const target = log.entityName

    if (kind === 'document') {
        const verb = ({
            upload: 'uploaded document',
            edit: 'updated document',
            verify: 'verified document',
            reject: 'rejected document',
            delete: 'removed document',
        } as Record<string, string>)[subKind ?? ''] ?? `${actionVerbFor(log.action)} document`
        return (
            <>
                <span className="text-muted-foreground"> {verb} </span>
                {target && <span className="font-medium text-foreground">{target}</span>}
            </>
        )
    }
    if (kind === 'attendance') {
        const at = typeof meta.at === 'string' ? formatPunchTime(meta.at) : ''
        const date = typeof meta.date === 'string' ? meta.date : ''
        const verb = ({
            'check-in': 'checked in',
            'check-out': 'checked out',
            'manual-punch': 'added a manual punch',
            'delete-punch': 'removed a punch',
            'update': 'updated attendance',
            'external-punch': 'recorded a biometric punch',
        } as Record<string, string>)[subKind ?? ''] ?? `${actionVerbFor(log.action)} attendance`
        const when = at || date
        return (
            <>
                <span className="text-muted-foreground"> {verb}</span>
                {when && <span className="text-muted-foreground"> at <span className="font-medium text-foreground tabular-nums">{when}</span></span>}
            </>
        )
    }
    if (kind === 'payroll') {
        // Salary / bank-detail edit (PATCH /employees/:id via Edit Payroll dialog)
        if (subKind === 'update') {
            return (
                <>
                    <span className="text-muted-foreground"> updated payroll details</span>
                    {changeCount > 0 && (
                        <span className="text-muted-foreground"> · {changeCount} field{changeCount === 1 ? '' : 's'}</span>
                    )}
                </>
            )
        }
        // Payslip generated by a payroll run
        const month = typeof meta.month === 'number' ? meta.month : null
        const year = typeof meta.year === 'number' ? meta.year : null
        const period = month && year ? `${String(month).padStart(2, '0')}/${year}` : ''
        const net = typeof meta.netSalary === 'number' ? meta.netSalary : null
        return (
            <>
                <span className="text-muted-foreground"> received {viewer === 'self' ? 'your ' : 'a '}payslip</span>
                {period && <span className="text-muted-foreground"> for <span className="font-medium text-foreground tabular-nums">{period}</span></span>}
                {net !== null && <span className="text-muted-foreground"> · net <span className="font-medium text-foreground tabular-nums">AED {net.toLocaleString()}</span></span>}
            </>
        )
    }
    if (kind === 'leave') {
        const verb = ({
            submit: 'submitted a leave request',
            approve: 'approved leave',
            reject: 'rejected leave',
            cancel: 'cancelled leave',
        } as Record<string, string>)[subKind ?? ''] ?? `${actionVerbFor(log.action)} leave`
        const leaveType = typeof meta.leaveType === 'string' ? meta.leaveType.replace(/_/g, ' ') : ''
        return (
            <>
                <span className="text-muted-foreground"> {verb}</span>
                {leaveType && <span className="text-muted-foreground"> · <span className="font-medium text-foreground capitalize">{leaveType}</span></span>}
            </>
        )
    }
    if (kind === 'loan') {
        const amount = typeof meta.amount === 'number' ? meta.amount : null
        const verb = ({
            request: 'requested a loan',
            approve: 'approved loan',
            reject: 'rejected loan',
            disburse: 'disbursed loan',
            installment: 'recorded a loan installment',
        } as Record<string, string>)[subKind ?? ''] ?? `${actionVerbFor(log.action)} loan`
        return (
            <>
                <span className="text-muted-foreground"> {verb}</span>
                {amount !== null && <span className="text-muted-foreground"> · <span className="font-medium text-foreground tabular-nums">AED {amount.toLocaleString()}</span></span>}
            </>
        )
    }
    if (kind === 'visa') {
        const verb = ({
            create: 'started a visa application',
            edit: 'updated visa application',
            advance: 'advanced visa stage',
            'advance-noop': 'reviewed visa stage',
            delete: 'removed visa application',
            cancel: 'cancelled visa application',
        } as Record<string, string>)[subKind ?? ''] ?? `${actionVerbFor(log.action)} visa`
        const toLabel = typeof meta.toStepLabel === 'string' ? meta.toStepLabel : ''
        return (
            <>
                <span className="text-muted-foreground"> {verb}</span>
                {toLabel && <span className="text-muted-foreground"> to <span className="font-medium text-foreground">{toLabel}</span></span>}
                {!toLabel && target && <span className="text-muted-foreground"> — <span className="font-medium text-foreground">{target}</span></span>}
            </>
        )
    }
    if (kind === 'transfer') {
        const fromDept = typeof meta.fromDepartment === 'string' ? meta.fromDepartment : ''
        const toDept = typeof meta.toDepartment === 'string' ? meta.toDepartment : ''
        return (
            <>
                <span className="text-muted-foreground"> transferred</span>
                {fromDept && toDept && (
                    <span className="text-muted-foreground">
                        {' from '}
                        <span className="font-medium text-foreground">{fromDept}</span>
                        {' to '}
                        <span className="font-medium text-foreground">{toDept}</span>
                    </span>
                )}
                {(!fromDept || !toDept) && target && (
                    <span className="text-muted-foreground"> effective <span className="font-medium text-foreground">{target}</span></span>
                )}
            </>
        )
    }
    if (kind === 'exit') {
        const verb = ({
            initiate: 'initiated exit',
            approve: 'approved exit',
            reject: 'rejected exit',
            'settlement-paid': 'marked settlement paid',
        } as Record<string, string>)[subKind ?? ''] ?? `${actionVerbFor(log.action)} exit`
        return <span className="text-muted-foreground"> {verb}</span>
    }
    if (kind === 'asset') {
        const verb = subKind === 'return' ? 'returned asset' : 'assigned asset'
        return (
            <>
                <span className="text-muted-foreground"> {verb} </span>
                {target && <span className="font-medium text-foreground">{target}</span>}
            </>
        )
    }
    if (kind === 'performance') {
        const verb = ({
            create: 'started a performance review',
            complete: 'completed a performance review',
            update: 'updated performance review',
            delete: 'removed performance review',
        } as Record<string, string>)[subKind ?? ''] ?? `${actionVerbFor(log.action)} performance review`
        const rating = typeof meta.overallRating === 'number' ? meta.overallRating : null
        return (
            <>
                <span className="text-muted-foreground"> {verb}</span>
                {target && <span className="text-muted-foreground"> · <span className="font-medium text-foreground">{target}</span></span>}
                {rating !== null && <span className="text-muted-foreground"> · rating <span className="font-medium text-foreground">{rating}</span></span>}
            </>
        )
    }
    if (kind === 'security') {
        const verb = ({
            'password-change': 'changed password',
            '2fa-enable': 'enabled two-factor authentication',
            '2fa-disable': 'disabled two-factor authentication',
            '2fa-backup-regenerate': 'regenerated backup codes',
        } as Record<string, string>)[subKind ?? ''] ?? `${actionVerbFor(log.action)} account security`
        return <span className="text-muted-foreground"> {verb}</span>
    }
    if (kind === 'profile') {
        // category → readable noun. The backend also sets entityName to the
        // same label for mirrored employee entries, so prefer that when present.
        const categoryLabel = ({
            bank_details: 'bank details',
            contact: 'contact details',
            personal: 'personal details',
        } as Record<string, string>)[typeof meta.category === 'string' ? meta.category : ''] ?? (target || 'profile')
        if (subKind === 'self-update') {
            return (
                <>
                    <span className="text-muted-foreground"> updated </span>
                    <span className="text-muted-foreground">
                        {changeCount > 0 ? `${changeCount} profile field${changeCount === 1 ? '' : 's'}` : 'their profile'}
                    </span>
                </>
            )
        }
        if (subKind === 'change-request') {
            return (
                <>
                    <span className="text-muted-foreground"> requested a change to </span>
                    <span className="font-medium text-foreground">{categoryLabel}</span>
                </>
            )
        }
        if (subKind === 'change-approved') {
            return (
                <>
                    <span className="text-muted-foreground"> approved {viewer === 'self' ? 'your ' : 'a '}</span>
                    <span className="font-medium text-foreground">{categoryLabel}</span>
                    <span className="text-muted-foreground"> change</span>
                </>
            )
        }
        if (subKind === 'change-rejected') {
            return (
                <>
                    <span className="text-muted-foreground"> rejected {viewer === 'self' ? 'your ' : 'a '}</span>
                    <span className="font-medium text-foreground">{categoryLabel}</span>
                    <span className="text-muted-foreground"> change</span>
                </>
            )
        }
    }

    return (
        <>
            <span className="text-muted-foreground"> {actionVerbFor(log.action)} </span>
            <span className="text-muted-foreground">
                {changeCount > 0 ? `${changeCount} field${changeCount === 1 ? '' : 's'}` : 'this record'}
            </span>
        </>
    )
}

function metaPillsFor(log: ActivityLog): { label: string; value: string }[] {
    const meta = (log.metadata ?? {}) as Record<string, unknown>
    const pills: { label: string; value: string }[] = []
    if (meta.kind === 'attendance' && typeof meta.locationName === 'string' && meta.locationName) {
        pills.push({ label: 'Location', value: String(meta.locationName) })
    }
    if (meta.kind === 'attendance' && typeof meta.deviceName === 'string' && meta.deviceName) {
        pills.push({ label: 'Device', value: String(meta.deviceName) })
    }
    if (meta.kind === 'document' && typeof meta.docType === 'string' && meta.docType) {
        pills.push({ label: 'Doc type', value: String(meta.docType) })
    }
    if (meta.kind === 'document' && typeof meta.reason === 'string' && meta.reason) {
        pills.push({ label: 'Reason', value: String(meta.reason) })
    }
    if (meta.kind === 'leave') {
        if (typeof meta.startDate === 'string' && meta.startDate) pills.push({ label: 'From', value: String(meta.startDate) })
        if (typeof meta.endDate === 'string' && meta.endDate) pills.push({ label: 'To', value: String(meta.endDate) })
        if (typeof meta.notes === 'string' && meta.notes) pills.push({ label: 'Notes', value: String(meta.notes) })
    }
    if (meta.kind === 'loan') {
        if (typeof meta.reason === 'string' && meta.reason) pills.push({ label: 'Reason', value: String(meta.reason) })
        if (typeof meta.notes === 'string' && meta.notes) pills.push({ label: 'Notes', value: String(meta.notes) })
        if (typeof meta.startDate === 'string' && meta.startDate) pills.push({ label: 'Starts', value: String(meta.startDate) })
    }
    if (meta.kind === 'transfer') {
        if (typeof meta.toDesignation === 'string' && meta.toDesignation) pills.push({ label: 'New designation', value: String(meta.toDesignation) })
        if (typeof meta.transferDate === 'string' && meta.transferDate) pills.push({ label: 'Effective', value: String(meta.transferDate) })
        if (typeof meta.reason === 'string' && meta.reason) pills.push({ label: 'Reason', value: String(meta.reason) })
    }
    if (meta.kind === 'exit') {
        if (typeof meta.exitType === 'string' && meta.exitType) pills.push({ label: 'Type', value: String(meta.exitType).replace(/_/g, ' ') })
        if (typeof meta.exitDate === 'string' && meta.exitDate) pills.push({ label: 'Exit date', value: String(meta.exitDate) })
        if (typeof meta.reason === 'string' && meta.reason) pills.push({ label: 'Reason', value: String(meta.reason) })
        if (meta.override === true) pills.push({ label: 'Override', value: 'yes' })
    }
    if (meta.kind === 'visa') {
        if (typeof meta.visaType === 'string' && meta.visaType) pills.push({ label: 'Visa type', value: String(meta.visaType).replace(/_/g, ' ') })
        if (typeof meta.fromStepLabel === 'string' && typeof meta.toStepLabel === 'string') pills.push({ label: 'Stage', value: `${meta.fromStepLabel} → ${meta.toStepLabel}` })
        if (typeof meta.reason === 'string' && meta.reason) pills.push({ label: 'Reason', value: String(meta.reason) })
    }
    if (meta.kind === 'asset') {
        if (typeof meta.assignedDate === 'string' && meta.assignedDate) pills.push({ label: 'Assigned', value: String(meta.assignedDate) })
        if (typeof meta.expectedReturnDate === 'string' && meta.expectedReturnDate) pills.push({ label: 'Due', value: String(meta.expectedReturnDate) })
        if (typeof meta.actualReturnDate === 'string' && meta.actualReturnDate) pills.push({ label: 'Returned', value: String(meta.actualReturnDate) })
    }
    if (meta.kind === 'payroll') {
        if (typeof meta.month === 'number' && typeof meta.year === 'number') {
            pills.push({ label: 'Period', value: `${String(meta.month).padStart(2, '0')}/${meta.year}` })
        }
    }
    if (meta.kind === 'profile' && meta.subKind === 'change-rejected' && typeof meta.reason === 'string' && meta.reason) {
        pills.push({ label: 'Reason', value: String(meta.reason) })
    }
    return pills
}

export interface ActivityRowProps {
    log: ActivityLog
    /** "hr" shows the actor name + IP; "self" shortens it for the employee portal. */
    viewer?: 'hr' | 'self'
}

export function ActivityRow({ log, viewer = 'hr' }: ActivityRowProps) {
    const [expanded, setExpanded] = React.useState(false)
    const changes = formatChangeEntries(log.changes)
    const visibleChanges = expanded ? changes : changes.slice(0, 3)
    const initials = (log.actorName ?? '?')
        .split(/\s+/)
        .filter(Boolean)
        .slice(0, 2)
        .map(n => n[0]?.toUpperCase() ?? '')
        .join('') || '?'
    const pills = metaPillsFor(log)
    const actorLabel = viewer === 'self' && log.actorName ? log.actorName : (log.actorName ?? 'System')

    return (
        <div className="px-4 py-3.5 hover:bg-muted/30 transition-colors">
            <div className="flex items-start gap-3">
                <div className="size-9 rounded-full bg-primary/10 text-primary text-[11px] font-semibold flex items-center justify-center shrink-0">
                    {initials}
                </div>
                <div className="flex-1 min-w-0">
                    <div className="flex items-start justify-between gap-3 flex-wrap">
                        <div className="min-w-0 flex-1">
                            <p className="text-sm leading-snug">
                                <span className="font-semibold text-foreground">{actorLabel}</span>
                                {buildActivityHeadline(log, changes.length, viewer)}
                            </p>
                            <div className="flex items-center gap-1.5 mt-1 text-[11px] text-muted-foreground flex-wrap">
                                <ActionBadge action={log.action} />
                                {viewer === 'hr' && log.actorRole && (
                                    <span className="capitalize">· {log.actorRole.replace(/_/g, ' ')}</span>
                                )}
                                {viewer === 'hr' && log.ipAddress && (
                                    <span className="font-mono text-[10px]">· {log.ipAddress}</span>
                                )}
                            </div>
                        </div>
                        <div className="text-right shrink-0">
                            <p className="text-[11px] text-muted-foreground tabular-nums">
                                {formatDateTime(log.createdAt)}
                            </p>
                        </div>
                    </div>

                    {changes.length > 0 && (
                        <div className="mt-2.5 rounded-lg bg-muted/30 border p-2.5 space-y-2">
                            {visibleChanges.map(c => (
                                <div key={c.key} className="grid grid-cols-[minmax(120px,180px)_1fr] gap-3 text-[12px] items-baseline">
                                    <span className="font-medium text-muted-foreground truncate">{c.label}</span>
                                    <div className="flex items-center gap-2 flex-wrap min-w-0">
                                        <span className="px-1.5 py-0.5 rounded bg-red-50 text-red-700 text-[11px] line-through break-all">
                                            {c.from}
                                        </span>
                                        <span className="text-muted-foreground shrink-0">→</span>
                                        <span className="px-1.5 py-0.5 rounded bg-emerald-50 text-emerald-700 text-[11px] font-medium break-all">
                                            {c.to}
                                        </span>
                                    </div>
                                </div>
                            ))}
                            {changes.length > 3 && (
                                <button
                                    type="button"
                                    onClick={() => setExpanded(v => !v)}
                                    className="text-[11px] text-primary hover:underline pt-0.5"
                                >
                                    {expanded ? 'Show less' : `Show ${changes.length - 3} more change${changes.length - 3 === 1 ? '' : 's'}`}
                                </button>
                            )}
                        </div>
                    )}
                    {pills.length > 0 && (
                        <div className="mt-2 flex items-center gap-1.5 flex-wrap">
                            {pills.map(p => (
                                <span key={p.label} className="inline-flex items-center gap-1 text-[11px] px-1.5 py-0.5 rounded bg-muted/60 text-foreground/80">
                                    <span className="text-muted-foreground">{p.label}:</span>
                                    <span className="font-medium">{p.value}</span>
                                </span>
                            ))}
                        </div>
                    )}
                </div>
            </div>
        </div>
    )
}

export interface ActivityFeedProps {
    logs: ActivityLog[]
    isLoading: boolean
    hasNextPage: boolean
    isFetchingNextPage: boolean
    fetchNextPage: () => void
    viewer?: 'hr' | 'self'
    emptyTitle?: string
    emptyDescription?: string
}

/**
 * Activity list + IntersectionObserver-driven infinite scroll. Owns its own
 * sentinel ref so callers can drop it into any container without wiring.
 */
export function ActivityFeed({
    logs,
    isLoading,
    hasNextPage,
    isFetchingNextPage,
    fetchNextPage,
    viewer = 'hr',
    emptyTitle = 'No activity yet',
    emptyDescription = 'Recent updates will appear here.',
}: ActivityFeedProps) {
    const sentinelRef = React.useRef<HTMLDivElement | null>(null)
    React.useEffect(() => {
        const el = sentinelRef.current
        if (!el) return
        const io = new IntersectionObserver((entries) => {
            if (entries[0]?.isIntersecting && hasNextPage && !isFetchingNextPage) {
                fetchNextPage()
            }
        }, { rootMargin: '200px' })
        io.observe(el)
        return () => io.disconnect()
    }, [hasNextPage, isFetchingNextPage, fetchNextPage])

    if (isLoading) {
        return (
            <div className="p-4 space-y-2">
                {[1, 2, 3, 4, 5].map(i => (
                    <div key={`act-skel-${i}`} className="h-16 rounded bg-muted animate-pulse" />
                ))}
            </div>
        )
    }
    if (!logs.length) {
        return (
            <div className="text-center py-12 text-muted-foreground">
                <History className="size-8 mx-auto mb-2 opacity-30" />
                <p className="text-sm font-medium">{emptyTitle}</p>
                <p className="text-xs mt-0.5">{emptyDescription}</p>
            </div>
        )
    }
    return (
        <div className="divide-y">
            {logs.map(log => <ActivityRow key={log.id} log={log} viewer={viewer} />)}
            <div ref={sentinelRef} className="h-6" />
            {isFetchingNextPage && (
                <div className="flex justify-center items-center gap-2 py-4 text-xs text-muted-foreground">
                    <Loader2 className="size-3 animate-spin" /> Loading more…
                </div>
            )}
            {!hasNextPage && logs.length >= 20 && (
                <div className="text-center py-3 text-[11px] text-muted-foreground/70">
                    End of activity
                </div>
            )}
        </div>
    )
}
